// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function GetAvailableVersions(arg1) {
  return window['go']['main']['App']['GetAvailableVersions'](arg1);
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetInstalledTools() {
  return window['go']['main']['App']['GetInstalledTools']();
}

export function GetInstalledVersions(arg1) {
  return window['go']['main']['App']['GetInstalledVersions'](arg1);
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function GetToolByID(arg1) {
  return window['go']['main']['App']['GetToolByID'](arg1);
}

export function GetToolState(arg1) {
  return window['go']['main']['App']['GetToolState'](arg1);
}

export function GetToolsByCategory(arg1) {
  return window['go']['main']['App']['GetToolsByCategory'](arg1);
}

export function InstallTool(arg1, arg2) {
  return window['go']['main']['App']['InstallTool'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchTools(arg1) {
  return window['go']['main']['App']['SearchTools'](arg1);
}

export function SetActiveVersion(arg1, arg2) {
  return window['go']['main']['App']['SetActiveVersion'](arg1, arg2);
}

export function UninstallTool(arg1, arg2) {
  return window['go']['main']['App']['UninstallTool'](arg1, arg2);
}

export function UpdateAllTools() {
  return window['go']['main']['App']['UpdateAllTools']();
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}
