// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CheckForUpdates():Promise<Record<string, boolean>>;

export function GetAvailableVersions(arg1:string):Promise<Array<domain.Version>>;

export function GetCatalog():Promise<Array<domain.Tool>>;

export function GetCategories():Promise<Array<string>>;

export function GetConfig():Promise<domain.Config>;

export function GetInstalledTools():Promise<Record<string, domain.ToolState>>;

export function GetInstalledVersions(arg1:string):Promise<Array<domain.InstalledVersion>>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function GetToolByID(arg1:string):Promise<domain.Tool>;

export function GetToolState(arg1:string):Promise<domain.ToolState>;

export function GetToolsByCategory(arg1:string):Promise<Array<domain.Tool>>;

export function InstallTool(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:domain.Config):Promise<void>;

export function SearchTools(arg1:string):Promise<Array<domain.Tool>>;

export function SetActiveVersion(arg1:string,arg2:string):Promise<void>;

export function UninstallTool(arg1:string,arg2:string):Promise<void>;

export function UpdateAllTools():Promise<void>;

export function UpdateTool(arg1:string):Promise<void>;
